import Head from 'next/head'
import Navbar from '@/components/Navbar/Navbar'
import Header from '@/components/Header/Header'
import About from '@/components/About/About'
import ChatBot from '@/components/ChatBot/ChatBot'

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Kula.ai clone by saurabh sen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="relative">
        <Navbar />
        <ChatBot />
        <Header />
        <About data={data.texts} />
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const result = await fetch("https://mocki.io/v1/ee762599-31ae-4a3d-a6c7-d596525945e1");
  const data = await result.json();

  return {
     props: { data } 
  };
}
